name: Report a bug
description: Report a bug or issue in Speedtest Tracker.
title: "[Bug] "
labels: ["🐛 bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! You should only use this form for issues, to request a change or feature use the [feature request form]().
  - type: checkboxes
    attributes:
      label: Pre-work
      description: Before opening an issue make sure you've checked the resources below first, any issues that could have been solved by reading
the docs or closed issues will be closed.
      options:
      - label: I have read the [docs](https://docs.speedtest-tracker.dev)
        required: true
      - label: I have searched existing open and closed issues
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
