name: Bug report
description: Report an issue with Speedtest Tracker.
title: "[Bug] "
labels: ["bug", "unverified"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! You should only use this form for issues, to request a change or feature use the [feature request form](https://github.com/alexjustesen/testing-gh-templates).
  - type: checkboxes
    attributes:
      label: Pre-work
      description: |
        Before opening an issue make sure you've checked the resources below first, any issues that could have been solved by reading the docs or closed issues will be closed.
      options:
      - label: I have read the [docs]().
        required: true
      - label: I have searched existing open and closed issues.
        required: true
      - label: I agree to follow this project's [Code of Conduct]()
        required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you experienced.
      placeholder: I went to the coffee pot and it was empty.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue.
      placeholder: |
        1. Go to the coffee pot.
        2. Make more coffee.
        3. Pour it into a cup.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Application Version
      description: What version of Speedtest Tracker are you using?
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      placeholder: Chrome, Firefox, Safari, etc.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
