name: Close Inactive Question Issues

on:
  schedule:
    # Runs at 10:00 AM UTC every day
    - cron: '0 10 * * *'
  
  # Optional: Allow manual trigger
  workflow_dispatch:

jobs:
  close-questions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Close inactive issues with 'question' label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get today's date and calculate the date 2 weeks ago
        two_weeks_ago=$(date -u -d '1 day ago' '+%Y-%m-%dT%H:%M:%SZ')
        
        # List issues with the 'question' label that were last updated before 2 weeks ago
        issues=$(gh issue list --label question --state open --search "updated:<$two_weeks_ago" --json number --jq '.[].number')
        
        if [[ -z "$issues" ]]; then
          echo "No issues found with the label 'question' that are inactive for more than 2 weeks."
        else
          # Add a comment and close each issue
          for issue in $issues; do
            echo "Processing issue #$issue"
            
            # Add a comment to the issue
            gh issue comment "$issue" --body "This issue is being closed due to inactivity for over 2 weeks. If you believe this issue is still relevant, feel free to reopen or create a new one."
            
            # Close the issue
            gh issue close "$issue"
          done
        fi
