name: Add Comment to Feature Issues
on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    # Only run if the added label is "feature"
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Add comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const message = `Thank you for submitting this feature request! 🚀
            
            Our team will review this request and evaluate it against our product roadmap.
            We'll update this issue as we make progress.
            
            In the meantime, please provide any additional context or use cases that might help us better understand the feature request.`;
            
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              body: message
            });